#!/usr/bin/ruby

## Psycho's .irbrc
## ================

# Get Current Path
irbrc_dir = File.expand_path File.dirname(File.symlink?(__FILE__) ? File.readlink(__FILE__) : __FILE__)


# Load Gems & IRB Settings
require 'irb/completion'
require 'irb/ext/save-history'

%w[rubygems looksee/shortcuts wirble awesome_print].each do |gem|
  begin
    require gem
  rescue LoadError
  end
end


# Load Other Ruby Scripts
%w[
  _irb_styles.rb
  _class_overrides.rb
  _custom_methods.rb
]
.each { |file| eval File.read "#{irbrc_dir}/#{file}" }

